### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by EHadoux** [ansoni/watir-extensions-element-screenshot#4]
Hi, are pure ruby or no dependencies constraints somewhat mandatory? 
I already have in my code rmagick so I rewrote (almost) yours and the gap of performance is huge. 
Maybe being able to choose would be a good thing?

Cheers

**Comment by ansoni** [comment]
Not a requirement, but having a no-dependency option is nice.  I'm all for a code snippet(code is so simple) or a pull request:-)
